// src/app/app/layout.tsx
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { auth } from "@clerk/nextjs/server";
import MainDock from "@/components/maindock";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function AppLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const { userId } = await auth();
	if (!userId) {
		redirect("/landing");
	}

	return (
		<div className="relative min-h-screen">
			<MainDock />
			{children}
		</div>
	);
}
