import Link from "next/link";
import { Plus } from "lucide-react";

import { listCourses } from "./actions";
import { courseRowToRecord } from "./course-data";
import { formatDate } from "./course-helpers";

export default async function CoursesIndexPage() {
	const rows = await listCourses();
	const courseEntries = rows
		.map((row) => {
			const course = courseRowToRecord(row);
			if (!course) {
				return null;
			}
			return { rowId: row.id, course };
		})
		.filter(
			(entry): entry is NonNullable<typeof entry> => entry !== null,
		);

	return (
		<main className="mx-auto flex w-full max-w-5xl flex-col gap-8 px-6 py-12">
			<section className="rounded-lg border border-border bg-card p-6 shadow-sm">
				<h1 className="text-3xl font-semibold">Courses</h1>
				<p className="mt-2 text-sm text-muted-foreground">
					All of your synced courses in one place. Select a course to drill into
					its autogenerated syllabus plan.
				</p>
			</section>

			<section className="grid gap-6 md:grid-cols-2">
				{courseEntries.length === 0 ? (
					<div className="col-span-full rounded-lg border border-dashed border-border/70 bg-muted/30 p-8 text-center text-sm text-muted-foreground">
						<span className="font-medium text-foreground">
							No courses yet.
						</span>{" "}
						Start a conversation with the assistant to generate your first
						plan.
					</div>
				) : (
					courseEntries.map(({ rowId, course }) => {
						const progress = Math.round(
							Math.max(0, Math.min(1, course.progress.completionPct)) * 100,
						);
						const calendar = course.plan?.calendar ?? [];
						const nextDate =
							calendar.length > 0 ? formatDate(calendar[0].date) : "TBD";
						const term = course.syllabusExtract?.term ?? "Term TBD";
						const instructor =
							course.syllabusExtract?.instructor ?? "Instructor TBD";
						const meetingTimes =
							(course.syllabusExtract?.meetingTimes ?? []).length > 0
								? course.syllabusExtract.meetingTimes.join(", ")
								: "TBD";

						return (
							<Link
								key={rowId}
								href={`/app/courses/${rowId}`}
								className="group rounded-lg border border-border bg-card p-5 shadow-sm transition hover:border-primary/60 hover:shadow-md focus:outline-none focus:ring-2 focus:ring-primary/40"
							>
								<div className="flex items-start justify-between gap-4">
									<div>
										<h2 className="text-xl font-semibold group-hover:text-primary">
											{course.title}
										</h2>
										<p className="mt-1 text-sm text-muted-foreground">
											{term} -{" "}
											<span className="font-medium">{instructor}</span>
										</p>
									</div>
									<span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium uppercase tracking-wide text-primary">
										{progress}% complete
									</span>
								</div>

								<div className="mt-4 space-y-3 text-sm text-muted-foreground">
									<p>
										<strong className="font-semibold text-foreground">
											Meetings:
										</strong>{" "}
										{meetingTimes}
									</p>
									<p>
										<strong className="font-semibold text-foreground">
											Next Date:
										</strong>{" "}
										{nextDate}
									</p>
								</div>
							</Link>
						);
					})
				)}
				<Link
					href="/app/courses/create-new-course"
					className="group flex min-h-[212px] flex-col items-center justify-center gap-4 rounded-lg border border-dashed border-border/80 bg-transparent p-5 text-center transition hover:border-primary/60 hover:bg-primary/5 focus:outline-none focus:ring-2 focus:ring-primary/40"
				>
					<span className="grid h-16 w-16 place-items-center rounded-full border border-dashed border-border/60 bg-background transition group-hover:border-primary/60 group-hover:text-primary">
						<Plus className="h-7 w-7" aria-hidden="true" />
						<span className="sr-only">Add a new course</span>
					</span>
					<div className="space-y-1">
						<p className="text-lg font-semibold text-foreground group-hover:text-primary">
							Add new course
						</p>
						<p className="text-sm text-muted-foreground">
							Start a new course with the intake assistant.
						</p>
					</div>
				</Link>
			</section>
		</main>
	);
}
